---
- name: Nginx server install and start 
  hosts: localhost
  become: true   # <-- Add this line

  tasks:
    - name: Install Nginx server
      yum:
        name: nginx
        state: present

    - name: Starting the nginx service
      service: 
        name: nginx
        state: started
        enabled: true
  

