---
- name: Tomcat server install and start
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Install Java Development Kit (JDK)
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Create tomcat group
      group:
        name: tomcat

    - name: Create tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false

    - name: Download Apache Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz
        dest: /opt/apache-tomcat-9.0.75.tar.gz
        mode: '0644'

    - name: Extract Tomcat tar file
      unarchive:
        src: /opt/apache-tomcat-9.0.75.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Change ownership of Tomcat directory
      file:
        path: /opt/apache-tomcat-9.0.75
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User=tomcat
          Group=tomcat

          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_HOME=/opt/apache-tomcat-9.0.75"

          ExecStart=/opt/apache-tomcat-9.0.75/bin/startup.sh
          ExecStop=/opt/apache-tomcat-9.0.75/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: true

